

from app.graphql.pdf_templates.strawberry.entity_schema_response import (
    EntityField,
    EntitySchema,
)


def build_entity_schemas() -> list[EntitySchema]:

    return [
        EntitySchema(
            entity_name="OrderLineItem",
            display_name="Order Line Item",
            fields=[
                EntityField(
                    name="lineNumber",
                    type="number",
                    nullable=False,
                    description="Line number",
                ),
                EntityField(
                    name="partNumber",
                    type="string",
                    nullable=True,
                    description="Part number",
                ),
                EntityField(
                    name="customerPartNumber",
                    type="string",
                    nullable=True,
                    description="Customer part number",
                ),
                EntityField(
                    name="description",
                    type="string",
                    nullable=True,
                    description="Item description",
                ),
                EntityField(
                    name="quantityOrdered",
                    type="number",
                    nullable=False,
                    description="Quantity ordered",
                ),
                EntityField(
                    name="quantityShipped",
                    type="number",
                    nullable=True,
                    description="Quantity shipped",
                ),
                EntityField(
                    name="quantityBackordered",
                    type="number",
                    nullable=True,
                    description="Quantity backordered",
                ),
                EntityField(
                    name="unitPrice",
                    type="number",
                    nullable=True,
                    description="Unit price",
                ),
                EntityField(
                    name="extendedPrice",
                    type="number",
                    nullable=True,
                    description="Extended price",
                ),
                EntityField(
                    name="discount",
                    type="number",
                    nullable=True,
                    description="Discount amount",
                ),
                EntityField(
                    name="notes",
                    type="string",
                    nullable=True,
                    description="Line item notes",
                ),
                EntityField(
                    name="consignmentFlag",
                    type="boolean",
                    nullable=True,
                    description="Consignment flag",
                ),
            ],
            related_entities=["Order", "Product"],
        ),
        EntitySchema(
            entity_name="InvoiceLineItem",
            display_name="Invoice Line Item",
            fields=[
                EntityField(
                    name="lineNumber",
                    type="number",
                    nullable=False,
                    description="Line number",
                ),
                EntityField(
                    name="partNumber",
                    type="string",
                    nullable=True,
                    description="Part number",
                ),
                EntityField(
                    name="description",
                    type="string",
                    nullable=True,
                    description="Item description",
                ),
                EntityField(
                    name="quantity",
                    type="number",
                    nullable=False,
                    description="Quantity",
                ),
                EntityField(
                    name="unitPrice",
                    type="number",
                    nullable=True,
                    description="Unit price",
                ),
                EntityField(
                    name="amount",
                    type="number",
                    nullable=True,
                    description="Line amount",
                ),
                EntityField(
                    name="commissionRate",
                    type="number",
                    nullable=True,
                    description="Commission rate",
                ),
                EntityField(
                    name="commissionAmount",
                    type="number",
                    nullable=True,
                    description="Commission amount",
                ),
            ],
            related_entities=["Invoice", "Order"],
        ),
        EntitySchema(
            entity_name="PreOpportunityDetail",
            display_name="Quote Line Item",
            fields=[
                EntityField(
                    name="lineNumber",
                    type="number",
                    nullable=False,
                    description="Line number",
                ),
                EntityField(
                    name="manufacturer",
                    type="string",
                    nullable=True,
                    description="Manufacturer name",
                ),
                EntityField(
                    name="partNumber",
                    type="string",
                    nullable=True,
                    description="Part number",
                ),
                EntityField(
                    name="description",
                    type="string",
                    nullable=True,
                    description="Item description",
                ),
                EntityField(
                    name="quantity",
                    type="number",
                    nullable=False,
                    description="Quantity",
                ),
                EntityField(
                    name="listPrice",
                    type="number",
                    nullable=True,
                    description="List price",
                ),
                EntityField(
                    name="multiplier",
                    type="number",
                    nullable=True,
                    description="Price multiplier",
                ),
                EntityField(
                    name="discount",
                    type="number",
                    nullable=True,
                    description="Discount amount",
                ),
                EntityField(
                    name="netPrice",
                    type="number",
                    nullable=True,
                    description="Net price",
                ),
                EntityField(
                    name="extendedPrice",
                    type="number",
                    nullable=True,
                    description="Extended price",
                ),
                EntityField(
                    name="leadTime",
                    type="string",
                    nullable=True,
                    description="Lead time",
                ),
                EntityField(
                    name="notes",
                    type="string",
                    nullable=True,
                    description="Line item notes",
                ),
            ],
            related_entities=["PreOpportunity", "Product"],
        ),
        EntitySchema(
            entity_name="FulfillmentOrderLineItem",
            display_name="Fulfillment Line Item",
            fields=[
                EntityField(
                    name="lineNumber",
                    type="number",
                    nullable=False,
                    description="Line number",
                ),
                EntityField(
                    name="partNumber",
                    type="string",
                    nullable=True,
                    description="Part number",
                ),
                EntityField(
                    name="description",
                    type="string",
                    nullable=True,
                    description="Item description",
                ),
                EntityField(
                    name="orderedQuantity",
                    type="number",
                    nullable=False,
                    description="Ordered quantity",
                ),
                EntityField(
                    name="shippingQuantity",
                    type="number",
                    nullable=True,
                    description="Shipping quantity",
                ),
                EntityField(
                    name="previouslyShipped",
                    type="number",
                    nullable=True,
                    description="Previously shipped",
                ),
                EntityField(
                    name="remaining",
                    type="number",
                    nullable=True,
                    description="Remaining quantity",
                ),
                EntityField(
                    name="binLocation",
                    type="string",
                    nullable=True,
                    description="Bin location",
                ),
                EntityField(
                    name="lotSerialNumber",
                    type="string",
                    nullable=True,
                    description="Lot/serial number",
                ),
                EntityField(
                    name="weight",
                    type="number",
                    nullable=True,
                    description="Item weight",
                ),
            ],
            related_entities=["FulfillmentOrder", "Order", "InventoryItem"],
        ),
        EntitySchema(
            entity_name="Company",
            display_name="Company",
            fields=[
                EntityField(
                    name="name",
                    type="string",
                    nullable=False,
                    description="Company name",
                ),
                EntityField(
                    name="customerNumber",
                    type="string",
                    nullable=True,
                    description="Customer number",
                ),
                EntityField(
                    name="contactName",
                    type="string",
                    nullable=True,
                    description="Contact name",
                ),
                EntityField(
                    name="address",
                    type="string",
                    nullable=True,
                    description="Street address",
                ),
                EntityField(
                    name="city",
                    type="string",
                    nullable=True,
                    description="City",
                ),
                EntityField(
                    name="state",
                    type="string",
                    nullable=True,
                    description="State",
                ),
                EntityField(
                    name="zip",
                    type="string",
                    nullable=True,
                    description="ZIP code",
                ),
                EntityField(
                    name="country",
                    type="string",
                    nullable=True,
                    description="Country",
                ),
                EntityField(
                    name="phone",
                    type="string",
                    nullable=True,
                    description="Phone number",
                ),
                EntityField(
                    name="email",
                    type="string",
                    nullable=True,
                    description="Email address",
                ),
                EntityField(
                    name="territory",
                    type="string",
                    nullable=True,
                    description="Territory",
                ),
            ],
            related_entities=["Contact", "CompanyAddress"],
        ),
        EntitySchema(
            entity_name="ShipToAddress",
            display_name="Ship To Address",
            fields=[
                EntityField(
                    name="locationName",
                    type="string",
                    nullable=True,
                    description="Location name",
                ),
                EntityField(
                    name="attention",
                    type="string",
                    nullable=True,
                    description="Attention line",
                ),
                EntityField(
                    name="streetAddress",
                    type="string",
                    nullable=True,
                    description="Street address",
                ),
                EntityField(
                    name="city",
                    type="string",
                    nullable=True,
                    description="City",
                ),
                EntityField(
                    name="state",
                    type="string",
                    nullable=True,
                    description="State",
                ),
                EntityField(
                    name="zip",
                    type="string",
                    nullable=True,
                    description="ZIP code",
                ),
                EntityField(
                    name="country",
                    type="string",
                    nullable=True,
                    description="Country",
                ),
                EntityField(
                    name="contactPhone",
                    type="string",
                    nullable=True,
                    description="Contact phone",
                ),
                EntityField(
                    name="contactEmail",
                    type="string",
                    nullable=True,
                    description="Contact email",
                ),
                EntityField(
                    name="deliveryInstructions",
                    type="string",
                    nullable=True,
                    description="Delivery instructions",
                ),
            ],
            related_entities=["FulfillmentOrder", "Order"],
        ),
        EntitySchema(
            entity_name="Job",
            display_name="Job",
            fields=[
                EntityField(
                    name="jobName",
                    type="string",
                    nullable=True,
                    description="Job name",
                ),
                EntityField(
                    name="jobNumber",
                    type="string",
                    nullable=True,
                    description="Job number",
                ),
                EntityField(
                    name="jobAddress",
                    type="string",
                    nullable=True,
                    description="Job address",
                ),
                EntityField(
                    name="jobType",
                    type="string",
                    nullable=True,
                    description="Job type",
                ),
                EntityField(
                    name="jobStatus",
                    type="string",
                    nullable=True,
                    description="Job status",
                ),
                EntityField(
                    name="gc",
                    type="string",
                    nullable=True,
                    description="General contractor",
                ),
                EntityField(
                    name="ec",
                    type="string",
                    nullable=True,
                    description="Electrical contractor",
                ),
                EntityField(
                    name="owner",
                    type="string",
                    nullable=True,
                    description="Owner",
                ),
                EntityField(
                    name="startDate",
                    type="date",
                    nullable=True,
                    description="Start date",
                ),
                EntityField(
                    name="endDate",
                    type="date",
                    nullable=True,
                    description="End date",
                ),
                EntityField(
                    name="jobValue",
                    type="number",
                    nullable=True,
                    description="Job value",
                ),
            ],
            related_entities=["Company"],
        ),
        EntitySchema(
            entity_name="FulfillmentOrder",
            display_name="Fulfillment Order",
            fields=[
                EntityField(
                    name="carrierName",
                    type="string",
                    nullable=True,
                    description="Carrier name",
                ),
                EntityField(
                    name="serviceLevel",
                    type="string",
                    nullable=True,
                    description="Service level",
                ),
                EntityField(
                    name="trackingNumber",
                    type="string",
                    nullable=True,
                    description="Tracking number",
                ),
                EntityField(
                    name="shipDate",
                    type="date",
                    nullable=True,
                    description="Ship date",
                ),
                EntityField(
                    name="estimatedDelivery",
                    type="date",
                    nullable=True,
                    description="Estimated delivery",
                ),
                EntityField(
                    name="freightTerms",
                    type="string",
                    nullable=True,
                    description="Freight terms",
                ),
                EntityField(
                    name="freightCost",
                    type="number",
                    nullable=True,
                    description="Freight cost",
                ),
                EntityField(
                    name="numberOfPackages",
                    type="number",
                    nullable=True,
                    description="Number of packages",
                ),
            ],
            related_entities=[],
        ),
        EntitySchema(
            entity_name="Warehouse",
            display_name="Warehouse",
            fields=[
                EntityField(
                    name="warehouseName",
                    type="string",
                    nullable=True,
                    description="Warehouse name",
                ),
                EntityField(
                    name="warehouseAddress",
                    type="string",
                    nullable=True,
                    description="Warehouse address",
                ),
                EntityField(
                    name="contactName",
                    type="string",
                    nullable=True,
                    description="Contact name",
                ),
                EntityField(
                    name="contactPhone",
                    type="string",
                    nullable=True,
                    description="Contact phone",
                ),
                EntityField(
                    name="contactEmail",
                    type="string",
                    nullable=True,
                    description="Contact email",
                ),
            ],
            related_entities=["ManufacturerProfile"],
        ),
        EntitySchema(
            entity_name="Invoice",
            display_name="Invoice",
            fields=[
                EntityField(
                    name="invoiceNumber",
                    type="string",
                    nullable=False,
                    description="Invoice number",
                ),
                EntityField(
                    name="invoiceDate",
                    type="date",
                    nullable=True,
                    description="Invoice date",
                ),
                EntityField(
                    name="invoiceTotal",
                    type="number",
                    nullable=True,
                    description="Invoice total",
                ),
                EntityField(
                    name="paymentsReceived",
                    type="number",
                    nullable=True,
                    description="Payments received",
                ),
                EntityField(
                    name="creditsApplied",
                    type="number",
                    nullable=True,
                    description="Credits applied",
                ),
                EntityField(
                    name="balanceDue",
                    type="number",
                    nullable=True,
                    description="Balance due",
                ),
                EntityField(
                    name="dueDate",
                    type="date",
                    nullable=True,
                    description="Due date",
                ),
            ],
            related_entities=["Order"],
        ),
        EntitySchema(
            entity_name="Credit",
            display_name="Credit",
            fields=[
                EntityField(
                    name="creditNumber",
                    type="string",
                    nullable=False,
                    description="Credit number",
                ),
                EntityField(
                    name="creditDate",
                    type="date",
                    nullable=True,
                    description="Credit date",
                ),
                EntityField(
                    name="originalInvoiceNumber",
                    type="string",
                    nullable=True,
                    description="Original invoice number",
                ),
                EntityField(
                    name="creditAmount",
                    type="number",
                    nullable=True,
                    description="Credit amount",
                ),
                EntityField(
                    name="reasonCode",
                    type="string",
                    nullable=True,
                    description="Reason code",
                ),
            ],
            related_entities=["Invoice"],
        ),
        EntitySchema(
            entity_name="CreditLineItem",
            display_name="Credit Line Item",
            fields=[
                EntityField(
                    name="lineNumber",
                    type="number",
                    nullable=False,
                    description="Line number",
                ),
                EntityField(
                    name="orderLineItemId",
                    type="string",
                    nullable=True,
                    description="Original order line item ID",
                ),
                EntityField(
                    name="partNumber",
                    type="string",
                    nullable=True,
                    description="Part number",
                ),
                EntityField(
                    name="description",
                    type="string",
                    nullable=True,
                    description="Item description",
                ),
                EntityField(
                    name="quantity",
                    type="number",
                    nullable=False,
                    description="Quantity",
                ),
                EntityField(
                    name="unitPrice",
                    type="number",
                    nullable=True,
                    description="Unit price",
                ),
                EntityField(
                    name="creditAmount",
                    type="number",
                    nullable=True,
                    description="Credit amount",
                ),
                EntityField(
                    name="reasonCode",
                    type="string",
                    nullable=True,
                    description="Reason code",
                ),
                EntityField(
                    name="commissionDeduction",
                    type="number",
                    nullable=True,
                    description="Commission deduction",
                ),
            ],
            related_entities=["Credit", "Invoice"],
        ),
        EntitySchema(
            entity_name="RmaItem",
            display_name="RMA Line Item",
            fields=[
                EntityField(
                    name="lineNumber",
                    type="number",
                    nullable=False,
                    description="Line number",
                ),
                EntityField(
                    name="partNumber",
                    type="string",
                    nullable=True,
                    description="Part number",
                ),
                EntityField(
                    name="description",
                    type="string",
                    nullable=True,
                    description="Item description",
                ),
                EntityField(
                    name="returnQuantity",
                    type="number",
                    nullable=False,
                    description="Return quantity",
                ),
                EntityField(
                    name="reason",
                    type="string",
                    nullable=True,
                    description="Return reason",
                ),
                EntityField(
                    name="condition",
                    type="string",
                    nullable=True,
                    description="Item condition",
                ),
                EntityField(
                    name="originalOrderReference",
                    type="string",
                    nullable=True,
                    description="Original order reference",
                ),
                EntityField(
                    name="disposition",
                    type="string",
                    nullable=True,
                    description="Disposition (restock, scrap, etc.)",
                ),
            ],
            related_entities=["RMA", "FulfillmentOrder"],
        ),
        EntitySchema(
            entity_name="CheckDetail",
            display_name="Commission Check Detail",
            fields=[
                EntityField(
                    name="lineNumber",
                    type="number",
                    nullable=False,
                    description="Line number",
                ),
                EntityField(
                    name="type",
                    type="string",
                    nullable=False,
                    description="Detail type (invoice, expense, credit)",
                ),
                EntityField(
                    name="referenceId",
                    type="string",
                    nullable=True,
                    description="Reference entity ID",
                ),
                EntityField(
                    name="referenceNumber",
                    type="string",
                    nullable=True,
                    description="Reference number (invoice, expense, or credit number)",
                ),
                EntityField(
                    name="description",
                    type="string",
                    nullable=True,
                    description="Description",
                ),
                EntityField(
                    name="amount",
                    type="number",
                    nullable=True,
                    description="Amount (positive for payments, negative for deductions)",
                ),
                EntityField(
                    name="orderNumber",
                    type="string",
                    nullable=True,
                    description="Related order number",
                ),
            ],
            related_entities=["CommissionCheck", "Invoice"],
        ),
    ]

