version: '3'

vars:
  SOURCES: app
  RUNNER: uv run

tasks:
  default:
    cmd:
      task: all

  lint:
    desc: Lint python source files
    cmds:
      - "{{.RUNNER}} ruff check --fix --select I {{.SOURCES}}"
      - "{{.RUNNER}} ruff format {{.SOURCES}}"

  typecheck:
    desc: Perform type-checking with basedpyright
    silent: true
    cmd: "{{.RUNNER}} basedpyright --level error {{.SOURCES}}"

  gql:
    desc: Export GraphQL Schema
    cmds:
      - >
        export PYTHONPATH=. && {{.RUNNER}} strawberry export-schema
        --app-dir app
        --output schema.graphql
        app.graphql.schemas.schema

  test:
    desc: Run tests with pytest
    cmd: "{{.RUNNER}} pytest"

  all:
    desc: Run the standard set of checks (lint, typecheck, gql)
    cmds:
      - task: lint
      - task: typecheck
      - task: gql

  all-ci:
    desc: Run the standard set of checks performed in CI
    cmds:
      - task: lint
      - task: typecheck
