from datetime import datetime
from decimal import Decimal
from uuid import UUID

import strawberry
from commons.db.v6.warehouse.shipment_requests import (
    ShipmentMethod,
    ShipmentPriority,
    ShipmentRequest,
    ShipmentRequestItem,
    ShipmentRequestStatus,
)

from app.core.strawberry.inputs import BaseInputGQL


@strawberry.input
class ShipmentRequestItemInput(BaseInputGQL[ShipmentRequestItem]):
    product_id: UUID
    quantity: Decimal

    def to_orm_model(self) -> ShipmentRequestItem:
        return ShipmentRequestItem(
            product_id=self.product_id,
            quantity=self.quantity,
            request_id=UUID(int=0),  # Dummy ID to satisfy type check
        )


@strawberry.input
class CreateShipmentRequestInput(BaseInputGQL[ShipmentRequest]):
    warehouse_id: UUID
    factory_id: UUID
    request_date: datetime
    priority: ShipmentPriority = ShipmentPriority.STANDARD
    method: ShipmentMethod | None = None
    status: ShipmentRequestStatus = ShipmentRequestStatus.PENDING
    notes: str | None = None
    items: list[ShipmentRequestItemInput] = strawberry.field(default_factory=list)

    def to_orm_model(self) -> ShipmentRequest:
        return ShipmentRequest(
            request_number="",  # Generated by service
            warehouse_id=self.warehouse_id,
            factory_id=self.factory_id,
            request_date=self.request_date,
            priority=self.priority,
            method=self.method,
            status=self.status,
            notes=self.notes,
        )


@strawberry.input
class UpdateShipmentRequestInput(BaseInputGQL[ShipmentRequest]):
    id: UUID
    factory_id: UUID | None = None
    priority: ShipmentPriority | None = None
    method: ShipmentMethod | None = None
    status: ShipmentRequestStatus | None = None
    notes: str | None = None
    items: list[ShipmentRequestItemInput] | None = None

    def to_orm_model(self) -> ShipmentRequest:
        # Create dummy object to satisfy constructor requirements
        request = ShipmentRequest(
            request_number="",
            warehouse_id=UUID(int=0),
            factory_id=UUID(int=0),
            request_date=datetime.min,
            priority=ShipmentPriority.STANDARD,
            status=ShipmentRequestStatus.PENDING,
        )
        request.id = self.id
        
        if self.factory_id:
            request.factory_id = self.factory_id
        if self.priority:
            request.priority = self.priority
        if self.method:
            request.method = self.method
        if self.status:
            request.status = self.status
        if self.notes:
            request.notes = self.notes
            
        return request
