"""init commit

Revision ID: 44932ca0481e
Revises:
Create Date: 2025-12-24 14:04:27.673657

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44932ca0481e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

schemas = ["pycommission", "pyfiles", "pycrm", "pyuser", "pycore"]


def upgrade() -> None:
    for schema in schemas:
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema};")

    # create extensions
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    # ### commands auto generated by Alembic - please adjust! ###
    _ = op.create_table(
        "job_statuses",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="pycrm",
    )
    _ = op.create_table(
        "manufacturer_order",
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="pycrm",
    )
    op.create_index(
        op.f("ix_pycrm_manufacturer_order_factory_id"),
        "manufacturer_order",
        ["factory_id"],
        unique=False,
        schema="pycrm",
    )
    _ = op.create_table(
        "pre_opportunity_balances",
        sa.Column(
            "subtotal",
            sa.Numeric(precision=10, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "total",
            sa.Numeric(precision=10, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "quantity",
            sa.Numeric(precision=10, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "discount",
            sa.Numeric(precision=10, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "discount_rate",
            sa.Numeric(precision=5, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="pycrm",
    )
    _ = op.create_table(
        "rbac_permissions",
        sa.Column("role", sa.Integer(), nullable=False),
        sa.Column("resource", sa.Integer(), nullable=False),
        sa.Column("privilege", sa.Integer(), nullable=False),
        sa.Column("option", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="pyuser",
    )

    # Seed default RBAC permissions
    # Roles: OWNER=1, ADMINISTRATOR=2, INSIDE_REP=3, OUTSIDE_REP=4
    # Resources: ADMIN=1, FACTORY=2, CUSTOMER=3, PRODUCT=4, QUOTE=5, ORDER=6,
    #            INVOICE=7, CHECK=8, CREDIT=9, EXPENSE=10, TASK=13
    # Privileges: VIEW=1, WRITE=2, DELETE=3
    # Options: OWN=1, ALL=2
    op.execute(
        """
        INSERT INTO pyuser.rbac_permissions (id, role, resource, privilege, option) VALUES
        -- OWNER permissions (full access to everything)
        (gen_random_uuid(), 1, 1, 1, 2), (gen_random_uuid(), 1, 1, 2, 2), (gen_random_uuid(), 1, 1, 3, 2),
        (gen_random_uuid(), 1, 2, 1, 2), (gen_random_uuid(), 1, 2, 2, 2), (gen_random_uuid(), 1, 2, 3, 2),
        (gen_random_uuid(), 1, 3, 1, 2), (gen_random_uuid(), 1, 3, 2, 2), (gen_random_uuid(), 1, 3, 3, 2),
        (gen_random_uuid(), 1, 4, 1, 2), (gen_random_uuid(), 1, 4, 2, 2), (gen_random_uuid(), 1, 4, 3, 2),
        (gen_random_uuid(), 1, 5, 1, 2), (gen_random_uuid(), 1, 5, 2, 2), (gen_random_uuid(), 1, 5, 3, 2),
        (gen_random_uuid(), 1, 6, 1, 2), (gen_random_uuid(), 1, 6, 2, 2), (gen_random_uuid(), 1, 6, 3, 2),
        (gen_random_uuid(), 1, 7, 1, 2), (gen_random_uuid(), 1, 7, 2, 2), (gen_random_uuid(), 1, 7, 3, 2),
        (gen_random_uuid(), 1, 8, 1, 2), (gen_random_uuid(), 1, 8, 2, 2), (gen_random_uuid(), 1, 8, 3, 2),
        (gen_random_uuid(), 1, 9, 1, 2), (gen_random_uuid(), 1, 9, 2, 2), (gen_random_uuid(), 1, 9, 3, 2),
        (gen_random_uuid(), 1, 10, 1, 2), (gen_random_uuid(), 1, 10, 2, 2), (gen_random_uuid(), 1, 10, 3, 2),
        (gen_random_uuid(), 1, 13, 1, 2), (gen_random_uuid(), 1, 13, 2, 2), (gen_random_uuid(), 1, 13, 3, 2),

        -- ADMINISTRATOR permissions (full access to everything)
        (gen_random_uuid(), 2, 1, 1, 2), (gen_random_uuid(), 2, 1, 2, 2), (gen_random_uuid(), 2, 1, 3, 2),
        (gen_random_uuid(), 2, 2, 1, 2), (gen_random_uuid(), 2, 2, 2, 2), (gen_random_uuid(), 2, 2, 3, 2),
        (gen_random_uuid(), 2, 3, 1, 2), (gen_random_uuid(), 2, 3, 2, 2), (gen_random_uuid(), 2, 3, 3, 2),
        (gen_random_uuid(), 2, 4, 1, 2), (gen_random_uuid(), 2, 4, 2, 2), (gen_random_uuid(), 2, 4, 3, 2),
        (gen_random_uuid(), 2, 5, 1, 2), (gen_random_uuid(), 2, 5, 2, 2), (gen_random_uuid(), 2, 5, 3, 2),
        (gen_random_uuid(), 2, 6, 1, 2), (gen_random_uuid(), 2, 6, 2, 2), (gen_random_uuid(), 2, 6, 3, 2),
        (gen_random_uuid(), 2, 7, 1, 2), (gen_random_uuid(), 2, 7, 2, 2), (gen_random_uuid(), 2, 7, 3, 2),
        (gen_random_uuid(), 2, 8, 1, 2), (gen_random_uuid(), 2, 8, 2, 2), (gen_random_uuid(), 2, 8, 3, 2),
        (gen_random_uuid(), 2, 9, 1, 2), (gen_random_uuid(), 2, 9, 2, 2), (gen_random_uuid(), 2, 9, 3, 2),
        (gen_random_uuid(), 2, 10, 1, 2), (gen_random_uuid(), 2, 10, 2, 2), (gen_random_uuid(), 2, 10, 3, 2),
        (gen_random_uuid(), 2, 13, 1, 2), (gen_random_uuid(), 2, 13, 2, 2), (gen_random_uuid(), 2, 13, 3, 2),

        -- INSIDE_REP permissions
        (gen_random_uuid(), 3, 2, 1, 2), (gen_random_uuid(), 3, 2, 2, 1), (gen_random_uuid(), 3, 2, 3, 1),
        (gen_random_uuid(), 3, 3, 1, 2), (gen_random_uuid(), 3, 3, 2, 1), (gen_random_uuid(), 3, 3, 3, 1),
        (gen_random_uuid(), 3, 4, 1, 2), (gen_random_uuid(), 3, 4, 2, 1), (gen_random_uuid(), 3, 4, 3, 1),
        (gen_random_uuid(), 3, 5, 1, 2), (gen_random_uuid(), 3, 5, 2, 2), (gen_random_uuid(), 3, 5, 3, 2),
        (gen_random_uuid(), 3, 6, 1, 2), (gen_random_uuid(), 3, 6, 2, 2), (gen_random_uuid(), 3, 6, 3, 2),
        (gen_random_uuid(), 3, 7, 1, 2), (gen_random_uuid(), 3, 7, 2, 2), (gen_random_uuid(), 3, 7, 3, 2),
        (gen_random_uuid(), 3, 8, 1, 2), (gen_random_uuid(), 3, 8, 2, 2), (gen_random_uuid(), 3, 8, 3, 2),
        (gen_random_uuid(), 3, 9, 1, 2), (gen_random_uuid(), 3, 9, 2, 2), (gen_random_uuid(), 3, 9, 3, 2),
        (gen_random_uuid(), 3, 10, 1, 2), (gen_random_uuid(), 3, 10, 2, 2), (gen_random_uuid(), 3, 10, 3, 2),
        (gen_random_uuid(), 3, 13, 1, 2), (gen_random_uuid(), 3, 13, 2, 2), (gen_random_uuid(), 3, 13, 3, 2),

        -- OUTSIDE_REP permissions (read-only factories/customers/products, own for transactions)
        (gen_random_uuid(), 4, 2, 1, 2),
        (gen_random_uuid(), 4, 3, 1, 2),
        (gen_random_uuid(), 4, 4, 1, 2),
        (gen_random_uuid(), 4, 5, 1, 1), (gen_random_uuid(), 4, 5, 2, 1), (gen_random_uuid(), 4, 5, 3, 1),
        (gen_random_uuid(), 4, 6, 1, 1), (gen_random_uuid(), 4, 6, 2, 1), (gen_random_uuid(), 4, 6, 3, 1),
        (gen_random_uuid(), 4, 7, 1, 1), (gen_random_uuid(), 4, 7, 2, 1), (gen_random_uuid(), 4, 7, 3, 1),
        (gen_random_uuid(), 4, 8, 1, 1), (gen_random_uuid(), 4, 8, 2, 1), (gen_random_uuid(), 4, 8, 3, 1),
        (gen_random_uuid(), 4, 9, 1, 1), (gen_random_uuid(), 4, 9, 2, 1), (gen_random_uuid(), 4, 9, 3, 1),
        (gen_random_uuid(), 4, 10, 1, 1), (gen_random_uuid(), 4, 10, 2, 1), (gen_random_uuid(), 4, 10, 3, 1),
        (gen_random_uuid(), 4, 13, 1, 1), (gen_random_uuid(), 4, 13, 2, 1), (gen_random_uuid(), 4, 13, 3, 1);
        """
    )

    _ = op.create_table(
        "rbac_role_settings",
        sa.Column("role", sa.SmallInteger(), nullable=False),
        sa.Column("commission", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role"),
        schema="pyuser",
    )

    op.execute(
        """
        INSERT INTO pyuser.rbac_role_settings (id, role, commission) VALUES
        (gen_random_uuid(), 1, true),   -- OWNER: has commission
        (gen_random_uuid(), 2, true),   -- ADMINISTRATOR: has commission
        (gen_random_uuid(), 3, true),   -- INSIDE_REP: has commission
        (gen_random_uuid(), 4, false),  -- OUTSIDE_REP: no commission
        (gen_random_uuid(), 5, false),  -- WAREHOUSE_MANAGER: no commission
        (gen_random_uuid(), 6, false),  -- WAREHOUSE_EMPLOYEE: no commission
        (gen_random_uuid(), 7, false);  -- DRIVER: no commission
        """
    )

    _ = op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("auth_provider_id", sa.String(), nullable=False),
        sa.Column("role", sa.SmallInteger(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("inside", sa.Boolean(), nullable=True),
        sa.Column("outside", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pyuser",
    )
    _ = op.create_table(
        "customers",
        sa.Column("company_name", sa.String(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("is_parent", sa.Boolean(), nullable=False),
        sa.Column("contact_email", sa.String(), nullable=True),
        sa.Column("contact_number", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["pyuser.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["pycore.customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycore",
    )
    _ = op.create_table(
        "product_uoms",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("division_factor", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("creation_type", sa.SmallInteger(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["pyuser.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycore",
    )
    _ = op.create_table(
        "campaigns",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("recipient_list_type", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.SmallInteger(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("email_subject", sa.String(length=500), nullable=True),
        sa.Column("email_body", sa.Text(), nullable=True),
        sa.Column("ai_personalization_enabled", sa.Boolean(), nullable=True),
        sa.Column("send_pace", sa.SmallInteger(), nullable=True),
        sa.Column("max_emails_per_day", sa.Integer(), nullable=True),
        sa.Column("scheduled_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("send_immediately", sa.Boolean(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["pyuser.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycrm",
    )
    _ = op.create_table(
        "companies",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("company_source_type", sa.SmallInteger(), nullable=False),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("parent_company_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["pyuser.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycrm",
    )
    _ = op.create_table(
        "contacts",
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("role", sa.String(length=100), nullable=True),
        sa.Column("territory", sa.String(length=100), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["pyuser.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycrm",
    )
    _ = op.create_table(
        "gmail_user_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("google_user_id", sa.String(length=255), nullable=False),
        sa.Column("google_email", sa.String(length=255), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("token_type", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["pyuser.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
        schema="pycrm",
    )
    _ = op.create_table(
        "jobs",
        sa.Column("job_name", sa.String(length=255), nullable=False),
        sa.Column("status_id", sa.UUID(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("job_type", sa.Text(), nullable=True),
        sa.Column("structural_details", sa.Text(), nullable=True),
        sa.Column("structural_information", sa.Text(), nullable=True),
        sa.Column("additional_information", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("requester_id", sa.UUID(), nullable=True),
        sa.Column("job_owner_id", sa.UUID(), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["pyuser.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["pycrm.job_statuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_name"),
        schema="pycrm",
    )
    _ = op.create_table(
        "link_relations",
        sa.Column("source_entity_type", sa.SmallInteger(), nullable=False),
        sa.Column("source_entity_id", sa.UUID(), nullable=False),
        sa.Column("target_entity_type", sa.SmallInteger(), nullable=False),
        sa.Column("target_entity_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["pyuser.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycrm",
    )
    _ = op.create_table(
        "notes",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("mentions", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["pyuser.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycrm",
    )
    _ = op.create_table(
        "o365_user_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("microsoft_user_id", sa.String(length=255), nullable=False),
        sa.Column("microsoft_email", sa.String(length=255), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column("expires_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("token_type", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["pyuser.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
        schema="pycrm",
    )
    _ = op.create_table(
        "spec_sheets",
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("upload_source", sa.String(length=50), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("file_url", sa.Text(), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("categories", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("folder_path", sa.String(length=500), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("highlight_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["pyuser.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycrm",
    )
    op.create_index(
        op.f("ix_pycrm_spec_sheets_factory_id"),
        "spec_sheets",
        ["factory_id"],
        unique=False,
        schema="pycrm",
    )
    op.create_index(
        op.f("ix_pycrm_spec_sheets_folder_path"),
        "spec_sheets",
        ["folder_path"],
        unique=False,
        schema="pycrm",
    )
    _ = op.create_table(
        "tasks",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("status", sa.SmallInteger(), nullable=False),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("assigned_to_id", sa.UUID(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("reminder_date", sa.Date(), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["pyuser.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycrm",
    )
    _ = op.create_table(
        "folders",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["pyuser.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["pyfiles.folders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pyfiles",
    )
    _ = op.create_table(
        "customer_split_rates",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("split_rate", sa.Numeric(), nullable=False),
        sa.Column("rep_type", sa.SmallInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["pycore.customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["pyuser.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycore",
    )
    _ = op.create_table(
        "campaign_criteria",
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column(
            "criteria_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("is_dynamic", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["pycrm.campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id"),
        schema="pycrm",
    )
    _ = op.create_table(
        "campaign_recipients",
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("contact_id", sa.UUID(), nullable=False),
        sa.Column("email_status", sa.SmallInteger(), nullable=False),
        sa.Column("sent_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("personalized_content", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["pycrm.campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["pycrm.contacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycrm",
    )
    _ = op.create_table(
        "campaign_send_logs",
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("send_date", sa.Date(), nullable=False),
        sa.Column("emails_sent", sa.Integer(), nullable=False),
        sa.Column("last_sent_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["pycrm.campaigns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", "send_date", name="uq_campaign_send_date"),
        schema="pycrm",
    )
    _ = op.create_table(
        "note_conversations",
        sa.Column("note_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["pyuser.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["pycrm.notes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycrm",
    )
    _ = op.create_table(
        "pre_opportunities",
        sa.Column("status", sa.SmallInteger(), nullable=False),
        sa.Column("entity_number", sa.String(length=255), nullable=False),
        sa.Column("entity_date", sa.Date(), nullable=False),
        sa.Column("exp_date", sa.Date(), nullable=True),
        sa.Column("revise_date", sa.Date(), nullable=True),
        sa.Column("accept_date", sa.Date(), nullable=True),
        sa.Column("sold_to_customer_id", sa.UUID(), nullable=False),
        sa.Column("sold_to_customer_address_id", sa.UUID(), nullable=True),
        sa.Column("bill_to_customer_id", sa.UUID(), nullable=True),
        sa.Column("bill_to_customer_address_id", sa.UUID(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("balance_id", sa.UUID(), nullable=False),
        sa.Column("payment_terms", sa.String(length=255), nullable=True),
        sa.Column("customer_ref", sa.String(length=255), nullable=True),
        sa.Column("freight_terms", sa.String(length=255), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["balance_id"],
            ["pycrm.pre_opportunity_balances.id"],
        ),
        sa.ForeignKeyConstraint(
            ["bill_to_customer_id"],
            ["pycore.customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["pyuser.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["pycrm.jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sold_to_customer_id"],
            ["pycore.customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("balance_id"),
        schema="pycrm",
    )
    _ = op.create_table(
        "spec_sheet_highlight_versions",
        sa.Column("spec_sheet_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["pyuser.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["spec_sheet_id"],
            ["pycrm.spec_sheets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycrm",
    )
    op.create_index(
        op.f("ix_pycrm_spec_sheet_highlight_versions_spec_sheet_id"),
        "spec_sheet_highlight_versions",
        ["spec_sheet_id"],
        unique=False,
        schema="pycrm",
    )
    _ = op.create_table(
        "task_conversations",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["pyuser.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["pycrm.tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycrm",
    )
    _ = op.create_table(
        "files",
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("file_path", sa.String(length=2000), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_entity_type", sa.SmallInteger(), nullable=True),
        sa.Column("file_type", sa.SmallInteger(), nullable=True),
        sa.Column("file_sha", sa.String(length=64), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("folder_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["pyuser.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["pyfiles.folders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pyfiles",
    )
    _ = op.create_table(
        "factories",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("account_number", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("logo_id", sa.UUID(), nullable=True),
        sa.Column("lead_time", sa.Integer(), nullable=True),
        sa.Column("payment_terms", sa.Integer(), nullable=True),
        sa.Column(
            "base_commission_rate", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column(
            "commission_discount_rate", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column(
            "overall_discount_rate", sa.Numeric(precision=5, scale=2), nullable=False
        ),
        sa.Column("additional_information", sa.Text(), nullable=True),
        sa.Column("freight_terms", sa.Text(), nullable=True),
        sa.Column("external_payment_terms", sa.Text(), nullable=True),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("freight_discount_type", sa.SmallInteger(), nullable=False),
        sa.Column("creation_type", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["pyuser.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["logo_id"],
            ["pyfiles.files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycore",
    )
    _ = op.create_table(
        "spec_sheet_highlight_regions",
        sa.Column("version_id", sa.UUID(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("width", sa.Float(), nullable=False),
        sa.Column("height", sa.Float(), nullable=False),
        sa.Column("shape_type", sa.String(length=50), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.Column("annotation", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["pycrm.spec_sheet_highlight_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycrm",
    )
    op.create_index(
        op.f("ix_pycrm_spec_sheet_highlight_regions_version_id"),
        "spec_sheet_highlight_regions",
        ["version_id"],
        unique=False,
        schema="pycrm",
    )
    _ = op.create_table(
        "factory_split_rates",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("split_rate", sa.Numeric(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["factory_id"],
            ["pycore.factories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["pyuser.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycore",
    )
    _ = op.create_table(
        "product_categories",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("commission_rate", sa.Numeric(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("grandparent_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["factory_id"],
            ["pycore.factories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["grandparent_id"],
            ["pycore.product_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["pycore.product_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycore",
    )
    _ = op.create_table(
        "products",
        sa.Column("factory_part_number", sa.String(), nullable=False),
        sa.Column("unit_price", sa.Numeric(), nullable=False),
        sa.Column("default_commission_rate", sa.Numeric(), nullable=False),
        sa.Column("factory_id", sa.UUID(), nullable=False),
        sa.Column("product_category_id", sa.UUID(), nullable=True),
        sa.Column("product_uom_id", sa.UUID(), nullable=True),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("approval_needed", sa.Boolean(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("creation_type", sa.SmallInteger(), nullable=False),
        sa.Column("upc", sa.String(length=50), nullable=True),
        sa.Column("default_divisor", sa.Numeric(), nullable=True),
        sa.Column("min_order_qty", sa.Numeric(), nullable=True),
        sa.Column("lead_time", sa.Integer(), nullable=True),
        sa.Column("unit_price_discount_rate", sa.Numeric(), nullable=True),
        sa.Column("commission_discount_rate", sa.Numeric(), nullable=True),
        sa.Column("approval_date", sa.Date(), nullable=True),
        sa.Column("approval_comments", sa.Text(), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["pyuser.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["factory_id"],
            ["pycore.factories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_category_id"],
            ["pycore.product_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_uom_id"],
            ["pycore.product_uoms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycore",
    )
    _ = op.create_table(
        "product_cpns",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("customer_part_number", sa.String(), nullable=False),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("commission_rate", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["pycore.customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["pycore.products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycore",
    )
    _ = op.create_table(
        "pre_opportunity_details",
        sa.Column("pre_opportunity_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("item_number", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "subtotal",
            sa.Numeric(precision=10, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "discount_rate",
            sa.Numeric(precision=5, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "discount",
            sa.Numeric(precision=10, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("factory_id", sa.UUID(), nullable=True),
        sa.Column("end_user_id", sa.UUID(), nullable=False),
        sa.Column("lead_time", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["end_user_id"],
            ["pycore.customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pre_opportunity_id"],
            ["pycrm.pre_opportunities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["pycore.products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["factory_id"],
            ["pycore.factories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="pycrm",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("pre_opportunity_details", schema="pycrm")
    op.drop_table("product_cpns", schema="pycore")
    op.drop_table("products", schema="pycore")
    op.drop_table("product_categories", schema="pycore")
    op.drop_table("factory_split_rates", schema="pycore")
    op.drop_index(
        op.f("ix_pycrm_spec_sheet_highlight_regions_version_id"),
        table_name="spec_sheet_highlight_regions",
        schema="pycrm",
    )
    op.drop_table("spec_sheet_highlight_regions", schema="pycrm")
    op.drop_table("factories", schema="pycore")
    op.drop_table("files", schema="pyfiles")
    op.drop_table("task_conversations", schema="pycrm")
    op.drop_index(
        op.f("ix_pycrm_spec_sheet_highlight_versions_spec_sheet_id"),
        table_name="spec_sheet_highlight_versions",
        schema="pycrm",
    )
    op.drop_table("spec_sheet_highlight_versions", schema="pycrm")
    op.drop_table("pre_opportunities", schema="pycrm")
    op.drop_table("note_conversations", schema="pycrm")
    op.drop_table("campaign_send_logs", schema="pycrm")
    op.drop_table("campaign_recipients", schema="pycrm")
    op.drop_table("campaign_criteria", schema="pycrm")
    op.drop_table("customer_split_rates", schema="pycore")
    op.drop_table("folders", schema="pyfiles")
    op.drop_table("tasks", schema="pycrm")
    op.drop_index(
        op.f("ix_pycrm_spec_sheets_folder_path"),
        table_name="spec_sheets",
        schema="pycrm",
    )
    op.drop_index(
        op.f("ix_pycrm_spec_sheets_factory_id"),
        table_name="spec_sheets",
        schema="pycrm",
    )
    op.drop_table("spec_sheets", schema="pycrm")
    op.drop_table("o365_user_tokens", schema="pycrm")
    op.drop_table("notes", schema="pycrm")
    op.drop_table("link_relations", schema="pycrm")
    op.drop_table("jobs", schema="pycrm")
    op.drop_table("gmail_user_tokens", schema="pycrm")
    op.drop_table("contacts", schema="pycrm")
    op.drop_table("companies", schema="pycrm")
    op.drop_table("campaigns", schema="pycrm")
    op.drop_table("product_uoms", schema="pycore")
    op.drop_table("customers", schema="pycore")
    op.drop_table("users", schema="pyuser")
    op.drop_table("rbac_role_settings", schema="pyuser")
    op.drop_table("rbac_permissions", schema="pyuser")
    op.drop_table("pre_opportunity_balances", schema="pycrm")
    op.drop_index(
        op.f("ix_pycrm_manufacturer_order_factory_id"),
        table_name="manufacturer_order",
        schema="pycrm",
    )
    op.drop_table("manufacturer_order", schema="pycrm")
    op.drop_table("job_statuses", schema="pycrm")
