from commons.db.v6.fulfillment import (
    CarrierType,
    FulfillmentActivity,
    FulfillmentActivityType,
    FulfillmentAssignment,
    FulfillmentAssignmentRole,
    FulfillmentMethod,
    FulfillmentOrder,
    FulfillmentOrderLineItem,
    FulfillmentOrderStatus,
    PackingBox,
    PackingBoxItem,
)

from app.graphql.v2.core.fulfillment.mutations import FulfillmentMutations
from app.graphql.v2.core.fulfillment.queries import FulfillmentQueries
from app.graphql.v2.core.fulfillment.repositories import (
    FulfillmentActivityRepository,
    FulfillmentAssignmentRepository,
    FulfillmentLineRepository,
    FulfillmentOrderRepository,
    PackingBoxItemRepository,
    PackingBoxRepository,
)
from app.graphql.v2.core.fulfillment.services import (
    FulfillmentAssignmentService,
    FulfillmentBackorderService,
    FulfillmentOrderService,
    FulfillmentPackingService,
    FulfillmentPickingService,
    FulfillmentShippingService,
)
from app.graphql.v2.core.fulfillment.strawberry import (
    AddAssignmentInput,
    AssignItemToBoxInput,
    AssignUserInput,
    BulkAssignmentInput,
    CancelBackorderInput,
    CompleteShippingInput,
    CreateFulfillmentLineItemInput,
    CreateFulfillmentOrderInput,
    CreatePackingBoxInput,
    FulfillmentActivityResponse,
    FulfillmentAssignmentResponse,
    FulfillmentOrderLineItemResponse,
    FulfillmentOrderResponse,
    FulfillmentStatsResponse,
    MarkManufacturerFulfilledInput,
    PackingBoxItemResponse,
    PackingBoxResponse,
    ShipToAddressInput,
    ShipToAddressResponse,
    SplitLineItemInput,
    UpdateFulfillmentOrderInput,
    UpdatePackingBoxInput,
    UpdatePickedQuantityInput,
)

__all__ = [
    # Models (from commons)
    "CarrierType",
    "FulfillmentActivity",
    "FulfillmentActivityType",
    "FulfillmentAssignment",
    "FulfillmentAssignmentRole",
    "FulfillmentMethod",
    "FulfillmentOrder",
    "FulfillmentOrderLineItem",
    "FulfillmentOrderStatus",
    "PackingBox",
    "PackingBoxItem",
    # Repositories
    "FulfillmentActivityRepository",
    "FulfillmentAssignmentRepository",
    "FulfillmentLineRepository",
    "FulfillmentOrderRepository",
    "PackingBoxItemRepository",
    "PackingBoxRepository",
    # Services
    "FulfillmentAssignmentService",
    "FulfillmentBackorderService",
    "FulfillmentOrderService",
    "FulfillmentPackingService",
    "FulfillmentPickingService",
    "FulfillmentShippingService",
    # GraphQL Types - Responses
    "FulfillmentActivityResponse",
    "FulfillmentAssignmentResponse",
    "FulfillmentOrderLineItemResponse",
    "FulfillmentOrderResponse",
    "FulfillmentStatsResponse",
    "PackingBoxItemResponse",
    "PackingBoxResponse",
    "ShipToAddressResponse",
    # GraphQL Types - Inputs
    "AddAssignmentInput",
    "AssignItemToBoxInput",
    "AssignUserInput",
    "BulkAssignmentInput",
    "CancelBackorderInput",
    "CompleteShippingInput",
    "CreateFulfillmentLineItemInput",
    "CreateFulfillmentOrderInput",
    "CreatePackingBoxInput",
    "MarkManufacturerFulfilledInput",
    "ShipToAddressInput",
    "SplitLineItemInput",
    "UpdateFulfillmentOrderInput",
    "UpdatePackingBoxInput",
    "UpdatePickedQuantityInput",
    # GraphQL Operations
    "FulfillmentQueries",
    "FulfillmentMutations",
]
